// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHY1J2NGlRmmSx03ka7gzqxv-OJlSkKw8',
    appId: '1:640018098360:web:7d8ce6796c0482b5b6ac4d',
    messagingSenderId: '640018098360',
    projectId: 'evion-platform',
    authDomain: 'evion-platform.firebaseapp.com',
    storageBucket: 'evion-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-xFnXB64aVK05nsn3zHXi3mYeEsqyzEA',
    appId: '1:640018098360:android:d8d6aa41395c9aabb6ac4d',
    messagingSenderId: '640018098360',
    projectId: 'evion-platform',
    storageBucket: 'evion-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZ_Hg1SAfRXTKrcHbUeGR3MsgVSpupus',
    appId: '1:640018098360:ios:2b2cea7e2b96d01fb6ac4d',
    messagingSenderId: '640018098360',
    projectId: 'evion-platform',
    storageBucket: 'evion-platform.firebasestorage.app',
    iosBundleId: 'com.example.evionAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZ_Hg1SAfRXTKrcHbUeGR3MsgVSpupus',
    appId: '1:640018098360:ios:2b2cea7e2b96d01fb6ac4d',
    messagingSenderId: '640018098360',
    projectId: 'evion-platform',
    storageBucket: 'evion-platform.firebasestorage.app',
    iosBundleId: 'com.example.evionAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHY1J2NGlRmmSx03ka7gzqxv-OJlSkKw8',
    appId: '1:640018098360:web:3bec51c0a1437719b6ac4d',
    messagingSenderId: '640018098360',
    projectId: 'evion-platform',
    authDomain: 'evion-platform.firebaseapp.com',
    storageBucket: 'evion-platform.firebasestorage.app',
  );
}
